stages:
  - build
  - test
  - publish

# build
build_package:
  image: amazoncorretto:11-alpine
  stage: build
  script:
    - sh gradlew assemble
  cache:
    paths:
      - .gradle/

# test
test_package:
  image: amazoncorretto:11-alpine
  stage: test
  script:
    - sh gradlew test
  allow_failure: false
  cache:
    paths:
      - .gradle/
  needs:
    - build_package

# publish
publish_package:
  image: amazoncorretto:11-alpine
  stage: publish
  script:
    - sh gradlew publishAndReleaseToMavenCentral --no-configuration-cache
  cache:
    paths:
      - .gradle/
  only:
    refs:
      - master
  needs:
    - test_package